name: Deploy Supabase Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/parse_pulse/**'
      - '.github/workflows/supabase-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://deb.supabase.com/install.sh | sh -s -- -d
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref bhxpstuyrdmocaxhjbiw
          supabase functions deploy parse_pulse
