name: Deploy Supabase Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/parse_pulse/**'
      - '.github/workflows/supabase-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy Supabase Function via Docker
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          docker run --rm \
            -e SUPABASE_ACCESS_TOKEN=$SUPABASE_ACCESS_TOKEN \
            -v "$PWD:/workspace" \
            -w /workspace \
            ghcr.io/supabase/cli:latest \
            sh -c "
              supabase link --project-ref bhxpstuyrdmocaxhjbiw &&
              supabase functions deploy parse_pulse
            "
