name: Deploy Supabase Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/parse_pulse/**'
      - '.github/workflows/supabase-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/download/v1.101.2/supabase_1.101.2_linux_x86_64.tar.gz | tar -xzf -
          mkdir -p ~/.supabase/bin
          mv supabase ~/.supabase/bin
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Deploy Supabase Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref bhxpstuyrdmocaxhjbiw
          supabase functions deploy parse_pulse
